apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: my-app-canary
  name: my-app-canary
  namespace: my-app-canary
spec:
  replicas: 2
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: {duration: 30s}
      - analysis:
          templates:
          - templateName: success-rate
          args:
          - name: service-name
            value: my-app-canary
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: my-app-canary
  template:
    metadata:
      labels:
        app: my-app-canary
    spec:
      containers:
      - name: my-app-canary
        image: jakuboskera/success-rate:100
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
