apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jakuboskera/argocd.git'
    path: argo-cd
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-cd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

