apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-bluegreen
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jakuboskera/argocd.git'
    path: my-app-bluegreen
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-app-bluegreen
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

