apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    path: charts/argo-rollouts
    targetRevision: HEAD
    helm:
      values: |
        argo-rollouts:
          controller:
            replicas: 1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
