apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    path: charts/kube-prometheus-stack/
    targetRevision: HEAD
    helm:
      values: |
        kube-prometheus-stack:
          prometheus:
            prometheusSpec:
              ruleSelectorNilUsesHelmValues: false
              serviceMonitorSelectorNilUsesHelmValues: false
              podMonitorSelectorNilUsesHelmValues: false
          grafana:
            enabled: false
          alertmanager:
            enabled: false
          defaultRules:
            create: false
          kubeApiServer:
            enabled: false
          kubelet:
            enabled: false
          kubeControllerManager:
            enabled: false
          coreDns:
            enabled: false
          kubeEtcd:
            enabled: false
          kubeScheduler:
            enabled: false
          kubeProxy:
            enabled: false
          kubeStateMetrics:
            enabled: false
          nodeExporter:
            enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
